Repository Igalia/wolvic, pull requests merged in 2024-01, with the labels that each got.

#1170 [Pico] Rename PicoXR device type to Pico4x
  app/src/common/shared/com/igalia/wolvic/ui/widgets/WebXRInterstitialWidget.java
  app/src/common/shared/com/igalia/wolvic/utils/DeviceType.java
  app/src/common/shared/com/igalia/wolvic/utils/EnvironmentUtils.java
  app/src/main/cpp/Device.h
  app/src/main/cpp/DeviceUtils.cpp
  app/src/main/cpp/ExternalVR.cpp
  app/src/openxr/cpp/DeviceDelegateOpenXR.cpp
  app/src/openxr/cpp/OpenXRInputMappings.h
Labels: pico

#1173 [VisionGlass] Use 3D operation mode & set a default height
  app/src/visionglass/cpp/DeviceDelegateVisionGlass.cpp
  app/src/visionglass/java/com/igalia/wolvic/PlatformActivity.java
Labels: vision glass

#1205 Fix typing in Android widgets without auto compose
  app/src/common/shared/com/igalia/wolvic/ui/widgets/KeyboardWidget.java
Labels: priority-high
